name: CI Tests

on:
  pull_request:
  push:
    branches:
      - main
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      e2e_test_filter:
        description: 'E2E test name filter (optional)'
        required: false
        default: ''

env:
  FOUNDRY_PROFILE: ci

jobs:
  # Check if tests should run
  check-run-conditions:
    name: Check Run Conditions
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      pr_sha: ${{ steps.get_pr.outputs.pr_sha }}
    steps:
      - name: Check conditions
        id: check
        run: |
          SHOULD_RUN="false"
          
          # Always run on push to main
          if [[ "${{ github.event_name }}" == "push" ]]; then
            SHOULD_RUN="true"
            echo "Running because of push to main"
          fi
          
          # Always run on workflow_dispatch
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            SHOULD_RUN="true"
            echo "Running because of workflow_dispatch"
          fi

          # Run on comment if it's a PR comment with /ci-authorize from a maintainer
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            if [[ "${{ contains(github.event.comment.body, '/ci-authorize') }}" == "true" ]]; then
              AUTHOR_ASSOC="${{ github.event.comment.author_association }}"
              if [[ "$AUTHOR_ASSOC" == "OWNER" || "$AUTHOR_ASSOC" == "MEMBER" || "$AUTHOR_ASSOC" == "COLLABORATOR" ]]; then
                SHOULD_RUN="true"
              fi
              echo "Running because of PR comment from maintainer"
            fi
          fi
          
          
          # # Run on PR if author is a maintainer
          # if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          #   AUTHOR_ASSOC="${{ github.event.pull_request.author_association }}"
          #   if [[ "$AUTHOR_ASSOC" == "OWNER" || "$AUTHOR_ASSOC" == "MEMBER" || "$AUTHOR_ASSOC" == "COLLABORATOR" ]]; then
          #     SHOULD_RUN="true"
          #   fi
          #   echo "Running because of PR from maintainer"
          # fi
          
          echo "should_run=$SHOULD_RUN" >> $GITHUB_OUTPUT
          echo "Should run CI: $SHOULD_RUN"
      
      - name: Get PR info for comment trigger
        if: github.event_name == 'issue_comment' && steps.check.outputs.should_run == 'true'
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.issue.number }}
            });
            core.setOutput('pr_sha', pr.data.head.sha);

      - name: Add reaction to comment
        if: github.event_name == 'issue_comment' && steps.check.outputs.should_run == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ github.event.comment.id }},
              content: 'rocket'
            });
  # Foundry Tests Job
  foundry-tests:
    name: Foundry Tests
    runs-on: ubuntu-latest
    needs: check-run-conditions
    if: needs.check-run-conditions.outputs.should_run == 'true'
    steps:
      - name: Dummy
        run: echo "Dummy"