name: Dummy

on:
  issue_comment:
    types: [created]

jobs:
  dummy:
    name: Dummy
    runs-on: ubuntu-latest
    steps:
      - name: Dummy
        env: 
          SECRET: ${{ secrets.DUMMY_SECRET }}
        run: echo $SECRET